name: Terraform Infrastructure Management

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  TF_VERSION: '1.5.7'
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_github_repository: ${{ github.repository }}
  TF_VAR_solana_rpc_url: ${{ secrets.SOLANA_RPC_URL }}
  TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}

jobs:
  terraform-checks:
    name: Terraform Validation and Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt -check -recursive

    - name: Terraform Init
      run: |
        cd terraform
        terraform init -backend=false

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: TFSec Security Scan
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: terraform
        soft_fail: true

    - name: Checkov Security Scan
      uses: bridgecrewio/checkov-action@master
      with:
        directory: terraform
        framework: terraform
        soft_fail: true
        output_format: github_failed_only
        download_external_modules: true

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-checks
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
    
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      id: plan
      run: |
        cd terraform
        terraform plan -out=tfplan -no-color | tee plan_output.txt
        
    - name: Comment PR with Plan
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require('./scripts/terraform-pr-comment.js');
          await script({github, context});

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-checks
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    
    permissions:
      contents: read
      id-token: write

    environment:
      name: production
      url: ${{ steps.output.outputs.cloud_run_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_wrapper: false

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Handle Existing Resources
      run: |
        cd terraform
        # Set required environment variables
        export TF_VAR_project_id="${{ secrets.GCP_PROJECT_ID }}"
        export TF_VAR_app_name="stb"
        
        # Run the import script
        ./handle_existing_resources.sh || echo "Import completed or skipped"

    - name: Terraform Apply with Target
      run: |
        cd terraform
        # First apply everything except Cloud Run to create secrets
        terraform apply -auto-approve -target=module.secret_manager -target=module.service_accounts -target=module.firestore -target=module.docker_build

    - name: Create Secret Versions
      run: |
        cd terraform
        
        # Get secret names from Terraform outputs
        WALLET_SECRET=$(terraform output -raw wallet_private_key_secret_name 2>/dev/null || echo "")
        LINE_TOKEN_SECRET=$(terraform output -raw line_channel_token_secret_name 2>/dev/null || echo "")
        LINE_USER_SECRET=$(terraform output -raw line_user_id_secret_name 2>/dev/null || echo "")
        
        # Create secret versions if they don't exist
        if [ -n "${WALLET_SECRET}" ]; then
          if [ -n "${{ secrets.WALLET_PRIVATE_KEY }}" ]; then
            echo "${{ secrets.WALLET_PRIVATE_KEY }}" | gcloud secrets versions add "${WALLET_SECRET}" --data-file=- || echo "Secret version already exists or creation failed"
          else
            echo "Creating placeholder for wallet private key secret"
            echo "PLACEHOLDER_WALLET_KEY" | gcloud secrets versions add "${WALLET_SECRET}" --data-file=- || echo "Secret version already exists or creation failed"
          fi
        fi
        
        if [ -n "${LINE_TOKEN_SECRET}" ]; then
          if [ -n "${{ secrets.LINE_CHANNEL_TOKEN }}" ]; then
            echo "${{ secrets.LINE_CHANNEL_TOKEN }}" | gcloud secrets versions add "${LINE_TOKEN_SECRET}" --data-file=- || echo "Secret version already exists or creation failed"
          else
            echo "Creating placeholder for LINE channel token secret"
            echo "PLACEHOLDER_LINE_TOKEN" | gcloud secrets versions add "${LINE_TOKEN_SECRET}" --data-file=- || echo "Secret version already exists or creation failed"
          fi
        fi
        
        if [ -n "${LINE_USER_SECRET}" ]; then
          if [ -n "${{ secrets.LINE_USER_ID }}" ]; then
            echo "${{ secrets.LINE_USER_ID }}" | gcloud secrets versions add "${LINE_USER_SECRET}" --data-file=- || echo "Secret version already exists or creation failed"
          else
            echo "Creating placeholder for LINE user ID secret"
            echo "PLACEHOLDER_LINE_USER" | gcloud secrets versions add "${LINE_USER_SECRET}" --data-file=- || echo "Secret version already exists or creation failed"
          fi
        fi

    - name: Terraform Apply Full
      run: |
        cd terraform
        # Now apply everything including Cloud Run
        terraform apply -auto-approve

    - name: Get Terraform Outputs
      id: output
      run: |
        cd terraform
        echo "cloud_run_url=$(terraform output -raw cloud_run_service_url)" >> $GITHUB_OUTPUT
        echo "scheduler_job=$(terraform output -raw scheduler_job_name)" >> $GITHUB_OUTPUT

    - name: Trigger Application Deployment
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: infrastructure-updated
        client-payload: '{"cloud_run_url": "${{ steps.output.outputs.cloud_run_url }}", "ref": "${{ github.ref }}"}'

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    
    permissions:
      contents: read
      id-token: write

    environment:
      name: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Destroy
      run: |
        cd terraform
        terraform destroy -auto-approve